"""Schema definitions used by API request and response handlers."""

from algotrading.api.schemas.backtesting import (
    BacktestComparison,
    BacktestComparisonRequest,
    BacktestRequest,
    BacktestResult,
    BacktestStatus,
    EquityPoint,
    PerformanceMetrics,
    TradeAction,
    TradeRecord,
)
from algotrading.api.schemas.common import APIError, APIResponse, PaginatedResponse
from algotrading.api.schemas.deployment import (
    DeploymentBacktestSummary,
    DeploymentCandidate,
    DeploymentGenerationSummary,
    DeploymentReadiness,
    DeploymentSelection,
    DeploymentValidationRequest,
    ReadinessCheck,
    ReadinessCheckStatus,
)
from algotrading.api.schemas.generations import (
    GenerationComparison,
    GenerationComparisonRequest,
    GenerationDetail,
    GenerationSummary,
)
from algotrading.api.schemas.models import (
    CoreRLModelConfig,
    ModelConfigBase,
    ModelConfigCreate,
    ModelConfigResponse,
    ModelConfigUpdate,
    ModelType,
    SupportingModelConfig,
)
from algotrading.api.schemas.optimizer import (
    AppliedSuggestionResponse,
    ApplySuggestionRequest,
    HyperparameterSuggestion,
    OptimizationResult,
    OptimizationSource,
    OptimizerAnalyzeRequest,
    SuggestionConfidence,
    SuggestionOutcomeStatus,
)
from algotrading.api.schemas.strategies import StrategyDetail, StrategyInfo
from algotrading.api.schemas.training import (
    TrainingJob,
    TrainingJobCreate,
    TrainingJobStatus,
    TrainingProgress,
    TrainingQueueReorderRequest,
)

__all__ = [
    "APIError",
    "APIResponse",
    "PaginatedResponse",
    "ReadinessCheckStatus",
    "ReadinessCheck",
    "DeploymentReadiness",
    "DeploymentValidationRequest",
    "DeploymentBacktestSummary",
    "DeploymentGenerationSummary",
    "DeploymentCandidate",
    "DeploymentSelection",
    "BacktestStatus",
    "TradeAction",
    "BacktestRequest",
    "TradeRecord",
    "PerformanceMetrics",
    "EquityPoint",
    "BacktestResult",
    "BacktestComparison",
    "BacktestComparisonRequest",
    "ModelType",
    "ModelConfigBase",
    "CoreRLModelConfig",
    "SupportingModelConfig",
    "ModelConfigCreate",
    "ModelConfigUpdate",
    "ModelConfigResponse",
    "StrategyInfo",
    "StrategyDetail",
    "GenerationSummary",
    "GenerationDetail",
    "GenerationComparison",
    "GenerationComparisonRequest",
    "SuggestionConfidence",
    "OptimizationSource",
    "SuggestionOutcomeStatus",
    "OptimizerAnalyzeRequest",
    "HyperparameterSuggestion",
    "OptimizationResult",
    "ApplySuggestionRequest",
    "AppliedSuggestionResponse",
    "TrainingJob",
    "TrainingJobCreate",
    "TrainingQueueReorderRequest",
    "TrainingJobStatus",
    "TrainingProgress",
]
