"""Service-layer exports for API endpoint handlers."""

from algotrading.api.services.backtest_service import (
    BacktestExecutionError,
    BacktestExecutionResult,
    BacktestExecutor,
    BacktestJobContext,
    BacktestNotFoundError,
    BacktestService,
    BacktestServiceError,
    BacktestValidationError,
    DefaultBacktestExecutor,
    create_default_backtest_service,
    get_backtest_service,
)
from algotrading.api.services.llm_optimizer import (
    LLMOptimizer,
    OptimizerServiceError,
    OptimizerSuggestionNotFoundError,
    OptimizerValidationError,
    create_default_optimizer_service,
    get_optimizer_service,
)
from algotrading.api.services.metrics_calculator import MetricsCalculator
from algotrading.api.services.model_service import (
    GenerationNotFoundError,
    InvalidModelStateError,
    ModelNotFoundError,
    ModelService,
    ModelServiceError,
    ModelValidationError,
    StrategyNotFoundError,
    create_default_model_service,
    get_model_service,
)
from algotrading.api.services.openai_client import (
    ChatCompletionClient,
    OpenAIClient,
    OpenAIClientError,
    OptimizerUnavailableError,
)
from algotrading.api.services.training_service import (
    TrainingJobNotFoundError,
    TrainingJobStateError,
    TrainingService,
    TrainingServiceError,
    create_default_training_service,
    get_training_service,
)

__all__ = [
    "BacktestExecutor",
    "BacktestExecutionResult",
    "BacktestJobContext",
    "BacktestService",
    "BacktestServiceError",
    "BacktestValidationError",
    "BacktestNotFoundError",
    "BacktestExecutionError",
    "DefaultBacktestExecutor",
    "MetricsCalculator",
    "create_default_backtest_service",
    "get_backtest_service",
    "ModelService",
    "ModelServiceError",
    "ModelValidationError",
    "ModelNotFoundError",
    "InvalidModelStateError",
    "StrategyNotFoundError",
    "GenerationNotFoundError",
    "create_default_model_service",
    "get_model_service",
    "ChatCompletionClient",
    "OpenAIClient",
    "OpenAIClientError",
    "OptimizerUnavailableError",
    "LLMOptimizer",
    "OptimizerServiceError",
    "OptimizerValidationError",
    "OptimizerSuggestionNotFoundError",
    "create_default_optimizer_service",
    "get_optimizer_service",
    "TrainingService",
    "TrainingServiceError",
    "TrainingJobNotFoundError",
    "TrainingJobStateError",
    "create_default_training_service",
    "get_training_service",
]
