"""REST endpoints for running and retrieving model backtests."""

from __future__ import annotations

from algotrading.api.schemas.backtesting import (
    BacktestComparison,
    BacktestComparisonRequest,
    BacktestRequest,
    BacktestResult,
    BacktestStatus,
    TradeRecord,
)
from algotrading.api.schemas.common import APIResponse, PaginatedResponse
from algotrading.api.services import GenerationNotFoundError, ModelNotFoundError
from algotrading.api.services.backtest_service import (
    BacktestNotFoundError,
    BacktestService,
    BacktestServiceError,
    BacktestValidationError,
    get_backtest_service,
)
from fastapi import APIRouter, Depends, HTTPException, Query, status

router = APIRouter(prefix="/backtests", tags=["backtesting"])


def _http_error(
    status_code: int,
    error: str,
    error_code: str,
    details: dict[str, object] | None = None,
) -> HTTPException:
    """Build a consistent HTTPException payload consumed by global handlers."""

    return HTTPException(
        status_code=status_code,
        detail={
            "error": error,
            "error_code": error_code,
            "details": details,
        },
    )


@router.post(
    "",
    response_model=APIResponse[BacktestResult],
    status_code=status.HTTP_201_CREATED,
)
async def run_backtest(
    request: BacktestRequest,
    service: BacktestService = Depends(get_backtest_service),
) -> APIResponse[BacktestResult]:
    """Run a backtest for a trained model generation."""

    try:
        result = await service.run_backtest(request)
    except ModelNotFoundError as exc:
        raise _http_error(404, str(exc), "MODEL_NOT_FOUND") from exc
    except GenerationNotFoundError as exc:
        raise _http_error(404, str(exc), "GENERATION_NOT_FOUND") from exc
    except BacktestValidationError as exc:
        raise _http_error(400, str(exc), "BACKTEST_VALIDATION_ERROR") from exc
    except BacktestServiceError as exc:
        raise _http_error(500, str(exc), "BACKTEST_SERVICE_ERROR") from exc

    return APIResponse(data=result, message="Backtest executed")


@router.get("", response_model=PaginatedResponse[BacktestResult])
def list_backtests(
    model_id: str | None = Query(default=None),
    generation_id: str | None = Query(default=None),
    result_status: BacktestStatus | None = Query(default=None, alias="status"),
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=100),
    service: BacktestService = Depends(get_backtest_service),
) -> PaginatedResponse[BacktestResult]:
    """List stored backtest results with optional filters."""

    try:
        return service.list_results(
            model_id=model_id,
            generation_id=generation_id,
            result_status=result_status,
            page=page,
            page_size=page_size,
        )
    except BacktestValidationError as exc:
        raise _http_error(400, str(exc), "BACKTEST_VALIDATION_ERROR") from exc


@router.post("/compare", response_model=APIResponse[BacktestComparison])
def compare_backtests(
    request: BacktestComparisonRequest,
    service: BacktestService = Depends(get_backtest_service),
) -> APIResponse[BacktestComparison]:
    """Compare multiple stored backtest results."""

    try:
        comparison = service.compare_backtests(request.backtest_ids)
    except BacktestNotFoundError as exc:
        raise _http_error(404, str(exc), "BACKTEST_NOT_FOUND") from exc
    except BacktestValidationError as exc:
        raise _http_error(400, str(exc), "BACKTEST_VALIDATION_ERROR") from exc

    return APIResponse(data=comparison)


@router.get("/{backtest_id}", response_model=APIResponse[BacktestResult])
def get_backtest(
    backtest_id: str,
    service: BacktestService = Depends(get_backtest_service),
) -> APIResponse[BacktestResult]:
    """Return detailed result data for one backtest."""

    try:
        result = service.get_result(backtest_id)
    except BacktestNotFoundError as exc:
        raise _http_error(404, str(exc), "BACKTEST_NOT_FOUND") from exc
    return APIResponse(data=result)


@router.get("/{backtest_id}/trades", response_model=APIResponse[list[TradeRecord]])
def get_backtest_trades(
    backtest_id: str,
    service: BacktestService = Depends(get_backtest_service),
) -> APIResponse[list[TradeRecord]]:
    """Return trade records generated by one backtest."""

    try:
        trades = service.get_trades(backtest_id)
    except BacktestNotFoundError as exc:
        raise _http_error(404, str(exc), "BACKTEST_NOT_FOUND") from exc
    return APIResponse(data=trades)


__all__ = ["router"]
