# Config settings for main.py script
ip_address: 127.0.0.1
port: 7497
account_number: DU1234567
pipeline: pipeline_0001
log_path: logs/
data_path: data/
task_selection: task4

# Settings for task 1
date_list:
  - 2024-11-21
  - 2024-11-22
  - 2024-11-23
  - 2024-11-24

# Settings for task 2
data_mode: historical
input_model: ppo_1
save_to_file: ppo_1
training_date_list:
  - 2024-11-21
  - 2024-11-22
  - 2024-11-23

# Settings for task 3
stream_data: real
trading_model: ppo_x

# Settings for task 4
backtest_model: ppo_1
backtest_date_list:
  - 2022-01-03
