# Config settings for main.py script
ip_address: 127.0.0.1
port: 7497
account_number: DU1234567
pipeline: pipeline_0002
log_path: logs/
data_path: data/
task_selection: task1
data_mode: historical

# Settings for task 1
date_list:
  - 2026-02-12

# Settings for task 2
input_model: ppo_x
save_to_file: ppo_x
training_date_list:
  - 2024-10-21
  - 2024-10-22

# Settings for task 3
stream_data: fake
trading_model: ppo_x

# Settings for task 4
backtest_model: ppo_x
backtest_date_list:
  - 2024-10-21
  - 2024-10-22
  - 2024-11-22
