# Config settings for main.py script
ip_address: 127.0.0.1
port: 7497
account_number: DU8392034
pipeline: pipeline_0001
log_path: logs/
data_path: data/
task_selection: task2

# Settings for task 1
date_list:
  - 2022-10-19
  - 2022-10-20
  - 2022-10-21
  - 2022-10-22
  - 2022-10-23
  - 2022-10-24
  - 2022-10-25

# Settings for task 2
data_mode: historical
input_model: ppo_x
save_to_file: ppo_y
training_date_list:
  - 2022-03-01
  - 2022-03-02
  - 2022-03-03
  - 2022-03-04
  - 2022-03-05
  - 2022-03-06
  - 2022-03-07

# Settings for task 3
stream_data: real
trading_model: ppo_x

# Settings for task 4
backtest_model: ppo_x
backtest_date_list:
  - 2022-01-03
