# Config settings for main.py script
ip_address: 127.0.0.1

port: 7497

pipeline: pipeline_0001

log_path: logs/

data_path: data/

task_selection: task2

# Settings for task 1
date_list:
  - 2024-01-13

# Settings for task 2
data_mode: historical

save_to_file: ppo_0001

training_date_list:
  - 2024-01-22
  - 2024-01-23
  - 2024-01-24