# Config settings for main.py script
ip_address: 127.0.0.1

port: 7497

pipeline: pipeline_0001

log_path: logs/

data_path: data/

task_selection: task3

# Settings for task 1
date_list:
  - 2022-04-01

# Settings for task 2
data_mode: historical

input_model: ppo_0000

save_to_file: ppo_0000

training_date_list:
  - 2023-01-01
  - 2023-01-02
  - 2023-01-03

# Settings for task 3
stream_data: fake

trading_model: ppo_0011

# Settings for task 4
backtest_model: ppo_0011

backtest_date_list:
  - 2024-04-30