# Config settings for main.py script
ip_address: 127.0.0.1

port: 7497

pipeline: pipeline_0001

log_path: logs/

data_path: data/

task_selection: task1

# Settings for task 1
date_list:
  - 2023-01-01
  - 2023-01-02
  - 2023-01-03
  - 2023-01-04
  - 2023-01-05
  - 2023-01-06
  - 2023-01-07
  - 2023-01-08
  - 2023-01-09
  - 2023-01-10

# Settings for task 2
data_mode: historical

input_model: ppo_0000

save_to_file: ppo_0000

training_date_list:
  - 2024-01-12
  - 2024-01-19

# Settings for task 4
backtest_model: ppo_0000

backtest_date_list:
  - 2024-01-12